- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  become: true

- name: Change root shell to Zsh
  user:
    name: root
    shell: /bin/zsh
  become: true

- name: Generate fr_FR.UTF-8 locale
  locale_gen:
    name: fr_FR.UTF-8
    state: present
  become: true

- name: Set system locale
  copy:
    dest: /etc/default/locale
    content: |
      LANG=fr_FR.UTF-8
      LC_ALL=fr_FR.UTF-8
  become: true

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Ensure chrony is installed
  apt:
    name: chrony
    state: present
  become: true
  notify: Restart chrony service

- name: Set swappiness to 10
  sysctl:
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present
    reload: yes
  become: true

- name: Set fs.file-max to 100000
  sysctl:
    name: fs.file-max
    value: "{{ file_max }}"
    state: present
    reload: yes
  become: true
