- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Upgrade the system
  apt:
    upgrade: dist
  become: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true

- name: Install essential packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - build-essential
      - docker.io
      - docker-compose
      - docker-compose-plugin
      - git
      - curl
      - zip
      - unzip
      - python3
      - python3-pip
      - python3-venv
      - ufw
      - htop
      - fail2ban
      - net-tools
      - lsof
      - gnupg
      - software-properties-common
    state: present
  become: true

- name: Allow SSH traffic
  ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Enable UFW firewall
  ufw:
    state: enabled
  become: true
