- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade the system
  become: true
  apt:
    upgrade: dist

- name: Install essential packages
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - build-essential
      - docker.io
      - docker-compose
      - git
      - curl
      - zip
      - unzip
      - python3
      - python3-pip
      - python3-venv
      - ufw
      - htop
      - fail2ban
      - net-tools
      - lsof
      - gnupg
      - software-properties-common
    state: present
