- name: Create Status Redirection directory
  file:
    path: "{{ status_redirection_directory }}"
    state: directory
    mode: '0755'
  become: true

- name: Allow Status Redirection port through UFW
  ufw:
    rule: allow
    port: "{{ status_redirection_port }}"
    proto: tcp
    comment: "Status Redirection"
  become: true

- name: Import Application ZIP
  copy:
    src: status-redirection.zip
    dest: "{{ status_redirection_directory }}/status-redirection.zip"
    mode: '0644'
  register: status_redirection_import_zip
  notify: Restart Status Redirection
  become: true

- name: Unzip Status Redirection application
  unarchive:
    src: "{{ status_redirection_directory }}/status-redirection.zip"
    dest: "{{ status_redirection_directory }}"
    remote_src: true
    mode: '0755'
  when: status_redirection_import_zip.changed
  notify: Restart Status Redirection
  become: true

- name: Import .env file for Status Redirection
  template:
    src: "{{ role_path }}/files/.env.j2"
    dest: "{{ status_redirection_directory }}/.env"
    mode: '0644'
  notify: Restart Status Redirection
  become: true

- name: Import Status Redirection service
  template:
    src: "{{ role_path }}/files/status-redirection.service.j2"
    dest: "/etc/systemd/system/status-redirection.service"
    mode: '0644'
  notify: Restart Status Redirection
  become: true

- name: Enable/Disable Status Redirection service
  systemd:
    daemon_reload: true
    name: status-redirection
    enabled: "{{ 'true' if status_redirection_enabled else 'false' }}"
    state: "{{ 'started' if status_redirection_enabled else 'stopped' }}"
  become: true
