- name: Create Nextcloud directory
  file:
    path: "{{ nextcloud_directory }}"
    state: directory
    mode: '0755'
  become: true

- name: Allow Nextcloud port through UFW
  ufw:
    rule: allow
    port: "{{ nextcloud_port }}"
    proto: tcp
    comment: "Nextcloud"
  become: true

- name: Import docker-compose.yml
  template:
    src: "{{ role_path }}/files/docker-compose.yml.j2"
    dest: "{{ nextcloud_directory }}/docker-compose.yml"
    mode: '0644'
  notify: Restart Nextcloud
  become: true

- name: Import Nextcloud service
  template:
    src: "{{ role_path }}/files/nextcloud.service.j2"
    dest: "/etc/systemd/system/nextcloud.service"
    mode: '0644'
  notify: Restart Nextcloud
  become: true

- name: Enable and start Nextcloud service
  systemd:
    daemon_reload: true
    name: nextcloud
    enabled: true
    state: started
  become: true
