- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: ups_enabled

- name: Install nut
  apt:
    name: nut
    state: present
  become: true
  when: ups_enabled
