- name: Bootstrap server as root
  hosts: all
  remote_user: root
  vars:
    ansible_user: root
  gather_facts: false
  become: false
  roles:
    - { role: base/bootstrap, tags: [base, bootstrap] }

- name: Configure server as deploy
  hosts: all
  remote_user: deploy
  become: true
  gather_facts: true

- name: Install packages
  hosts: all
  roles:
    - { role: base/packages, tags: [base, packages] }

- name: Setup settings
  hosts: all
  roles:
    - { role: base/settings, tags: [base, settings] }

- name: Setup user
  hosts: all
  roles:
    - { role: base/user, tags: [base, user] }

