- name: Crafty Controller
  hosts: all
  roles:
    - { role: container_management/crafty, tags: [container_management, crafty] }

- name: Portainer
  hosts: all
  roles:
    - { role: container_management/portainer, tags: [container_management, portainer] }

- name: Jenkins
  hosts: all
  roles:
    - { role: container_management/jenkins, tags: [container_management, jenkins] }
