- name: Glances
  hosts: all
  roles:
    - { role: monitoring_logs/glances, tags: [monitoring_logs, glances] }

- name: NTFY
  hosts: all
  roles:
    - { role: monitoring_logs/ntfy, tags: [monitoring_logs, ntfy] }

- name: Uptime Kuma
  hosts: all
  roles:
    - { role: monitoring_logs/uptime_kuma, tags: [monitoring_logs, uptime_kuma] }

- name: Dozzle
  hosts: all
  roles:
    - { role: monitoring_logs/dozzle, tags: [monitoring_logs, dozzle] }
