- name: Enable and start NUT services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - nut-server
    - nut-client
  become: true
  when: ups_enabled
